##############################################################################
#
#     PARSERTEST
#
#     Copyright (c) 2007-2008 Rehno Lindeque. All rights reserved.
#
##############################################################################

user_build_dir = '../../build'
user_src_dir = '../../src'
user_scriptname = 'ParserTest'

execfile('CommonSConscript', globals())
